export default {
  locale: 'en', seo: { title: 'JC Cabarcas Ingeniería SAS | Engineering, Energy & Technology', description: 'JC Cabarcas Ingeniería SAS delivers integrated engineering, solar energy and technology solutions for national and international projects from Barranquilla, Colombia.', ogDescription: 'Engineering, solar energy and technology for projects that transcend borders.' },
  nav: { label: 'Main navigation', open: 'Open menu', close: 'Close menu', home: 'Home', items: [['nosotros', 'About'], ['soluciones', 'Solutions'], ['proyectos', 'Projects'], ['sectores', 'Industries'], ['tecnologia', 'Technology'], ['cotizar', 'Get a quote'], ['contacto', 'Contact']], cta: 'Start a project' }, language: { label: 'Select language', es: 'Spanish', en: 'English', other: 'Other languages', otherLabel: 'Open additional languages', menuTitle: 'Languages', official: 'Official translation' },
  hero: { kicker: 'JC CABARCAS INGENIERÍA', line1: 'We design', line2: 'the future.', subtitle: 'Engineering, energy and technology for projects that transcend borders.', solutions: 'Explore our solutions', quote: 'Get a project quote', explore: 'Explore', location: 'Barranquilla · Colombia' },
  pillars: { eyebrow: 'One integrated vision', intro: 'Three capabilities working as one to take every project further.', items: [{ number: '01', title: 'Engineering', text: 'Design, consulting, technical supervision and execution grounded in engineering rigor.', href: '#ingenieria' }, { number: '02', title: 'Energy', text: 'Solar systems and energy management for a more efficient future.', href: '#energia' }, { number: '03', title: 'Technology', text: 'Software, automation and intelligence that connect operations.', href: '#tecnologia' }] },
  engineering: { eyebrow: '01 · Engineering', title: 'Technical rigor for projects built to perform.', intro: 'We design, supervise and deliver infrastructure solutions with an integrated approach—from early-stage studies through commissioning.', quoteType: 'Engineering', cta: 'Discuss an engineering solution', groups: [
    { title: 'Electrical & Civil Engineering', icon: 'bolt', items: ['Electrical design', 'Low- and medium-voltage networks', 'Substations and transformers', 'Switchboards and service connections', 'Lighting and public lighting', 'Grounding systems', 'RETIE-compliant designs and single-line diagrams', 'Conduits and civil works'] },
    { title: 'Automation & Infrastructure', icon: 'grid', items: ['Automation and control', 'Voice and data systems', 'Structured cabling', 'CCTV systems', 'Refrigeration', 'Electrical maintenance', 'Construction and remodeling', 'Power quality and reactive compensation'] },
    { title: 'Technical Supervision', icon: 'check', items: ['Construction supervision and monitoring', 'QA/QC, HSE and environmental oversight', 'Design and execution supervision', 'Budget control', 'Inspection and regulatory compliance', 'Procurement and supply audits'] },
    { title: 'Project Management & Consulting', icon: 'chart', items: ['Project planning and evaluation', 'Contract management', 'Budget control', 'Engineering and construction consulting', 'Procurement and sourcing', 'Feasibility, environmental and topographic studies'] },
  ] },
  solar: { eyebrow: '02 · Energy', title1: 'Solar energy.', title2: 'Engineered to perform.', intro: 'We turn solar potential into reliable, measurable systems designed around the real needs of homes, businesses and infrastructure.', from: 'From feasibility', to: 'to operation', process: 'One team to assess, design, implement and maintain.', quoteType: 'Solar Energy', cta: 'Design my solar system', groups: [
    { title: 'Photovoltaic Solutions', text: 'Residential, commercial and industrial', items: ['Grid-tied, off-grid and hybrid systems', 'Solar panels, inverters and batteries', 'BESS, backup power and microgrids', 'Utility-scale solar plants'] },
    { title: 'Specialized Applications', text: 'Energy where it is needed', items: ['Solar pumping and irrigation', 'Agriculture and rural communities', 'Solar lighting and public lighting', 'Solar carports and electric mobility', 'Telecommunications and remote sensors'] },
    { title: 'Studies & Engineering Design', text: 'Engineering-led decisions', items: ['Consumption, irradiation and feasibility studies', 'Photovoltaic system sizing', 'Financial analysis, ROI and savings', 'Detailed engineering and calculations', 'Electrical protection and structural design'] },
    { title: 'Operations & Energy Efficiency', text: 'Performance throughout the system lifecycle', items: ['Inspection, cleaning and diagnostics', 'Thermography and performance measurement', 'Preventive and corrective maintenance', 'Remote monitoring', 'Energy audits and optimization'] },
  ] },
  technology: { eyebrow: '03 · Technology', title: 'Technology that solves. Software that connects.', intro: 'We build digital products and intelligent systems around real operations—solutions designed to scale with every organization.', quoteType: 'Software', cta: 'Discuss a technology solution', groups: [
    { title: 'Web Development', tag: 'Digital experiences', items: ['Corporate websites', 'Landing pages and e-commerce', 'Digital catalogs and booking systems', 'Portals, payments and dashboards'] }, { title: 'Application Development', tag: 'Connected products', items: ['Web and mobile applications', 'Android and iOS', 'Enterprise platforms', 'Administrative systems'] }, { title: 'Enterprise Software', tag: 'Efficient operations', items: ['CRM and inventory systems', 'Projects and work orders', 'Maintenance and administration', 'APIs, databases and process automation'] }, { title: 'AI + IoT', tag: 'Applied intelligence', items: ['Chatbots and business assistants', 'Analytics and document processing', 'Sensors and telemetry', 'Smart buildings, automation and control'] },
  ] },
  smart: { eyebrow: 'Integrated solution', title1: 'Smart', title2: 'energy.', intro: 'We design energy systems that can be monitored from anywhere.', description: 'We combine electrical engineering, solar generation and purpose-built software to visualize generation, consumption, batteries, savings, alerts, history, forecasts and equipment status.', cta: 'Build an integrated solution', quoteType: 'Software', demo: 'Visual demonstration · Not real customer data', center: 'Energy control center', normal: 'Operating normally', metrics: [['Today’s production', '148.6', 'kWh'], ['Consumption', '127.4', 'kWh'], ['Monthly savings', 'COP 3,840,000', ''], ['Battery', '82', '%'], ['CO₂ avoided', '1.24', 'tonnes'], ['Tomorrow’s forecast', '156', 'kWh']], online: 'System online', conceptual: 'Concept view' },
  sectors: { eyebrow: 'Industries', title: 'Expertise that adapts to every environment.', items: ['Industrial', 'Commercial', 'Residential', 'Energy', 'Construction', 'Hospitality', 'Agriculture', 'Telecommunications', 'Infrastructure', 'Public sector'] },
  about: { eyebrow: 'About us', title: 'One company. Three disciplines. One vision.', intro: 'Based in Barranquilla, we see engineering as a platform for transformation. We combine technical expertise, sustainable energy and technology development to build coherent end-to-end solutions.', missionLabel: 'Mission', mission: 'To be a strategic partner to our clients through integrated engineering, energy and technology solutions that improve project efficiency, reliability and sustainability.', visionLabel: 'Vision', vision: 'To become a recognized company in integrated engineering, energy and technology solutions, known for innovation, quality and the ability to turn complex needs into efficient, sustainable outcomes.', valuesLabel: 'Our values', values: ['Integrity', 'Commitment', 'Customer satisfaction', 'Innovation', 'Continuous improvement', 'Excellence'] },
  global: { eyebrow: 'Global vision', title: 'Born in Colombia. Designed for a connected world.', description: 'We combine technical expertise, energy and technology with a global outlook to develop solutions that adapt to different industries, markets and scales.', capabilitiesLabel: 'Adaptable capabilities', capabilities: ['Engineering & consulting', 'Energy', 'Software', 'Automation'], cta: 'Let’s discuss your project' },
  projects: { eyebrow: 'Projects', title: 'A space for documented, real-world results.', intro: 'This section is ready to feature verified projects as their information becomes available.', placeholder: 'COMING SOON · PLACEHOLDER', cards: ['Engineering & infrastructure', 'Solar energy', 'Applied technology'], description: 'Prepared for verified scope, location, solution and outcomes.' },
  quote: { eyebrow: 'Let’s talk', title1: 'Tell us about', title2: 'your project.', intro: 'Tell us about the challenge, context and solution you need. Our team will review the information and help define the next step.', direct: 'Or message us on WhatsApp', fields: { name: 'Name', company: 'Company', email: 'Email', phone: 'Phone', type: 'Project type', description: 'Project description' }, placeholders: { name: 'Your name', company: 'Company name', email: 'email@company.com', phone: '305 555 1234', type: 'Select an option', description: 'Briefly tell us what you need...' }, types: ['Engineering', 'Solar Energy', 'Electrical Installations', 'Technical Supervision', 'Automation', 'Website', 'Application', 'Software', 'Other'], submit: 'Request a consultation', validating: 'Validating…', ready: 'Your request is ready. WhatsApp opened in a new tab so you can confirm and send it.', blocked: 'Your request is ready. Your browser blocked the new tab;', openWhatsapp: 'open WhatsApp here', error: 'Please review the highlighted fields before continuing.', privacy: 'We will prepare your request in WhatsApp. Your information is not stored yet.', errors: { name: 'Please enter your name.', company: 'Please enter your company name.', emailRequired: 'Please enter your email address.', emailInvalid: 'Please enter a valid email address.', phoneRequired: 'Please enter a contact phone number.', phoneInvalid: 'Please enter a valid international phone number.', country: 'Please select your country.', type: 'Please select a project type.', description: 'Please provide a brief project description.' }, message: { greeting: 'Hello, JC Cabarcas Ingeniería.', request: 'I would like to request a consultation for a project.', name: 'Name', company: 'Company', country: 'Country', phone: 'Phone', email: 'Email', type: 'Project type', description: 'Description', closing: 'I look forward to hearing from you.' } },
  country: { trigger: 'Country and calling code', searchLabel: 'Search country', searchPlaceholder: 'Search by country, ISO or code…', listLabel: 'Countries and calling codes', empty: 'No countries match your search.' }, contact: { label: 'Contact', international: 'Supporting national and international projects.' },
  footer: { description: 'We integrate engineering, renewable energy and technology to turn complex projects into efficient solutions.', explore: 'Explore', contact: 'Contact', rights: 'All rights reserved.', claim: 'Engineering · Energy · Technology', whatsappLabel: 'Contact us on WhatsApp', whatsapp: 'Let’s talk', whatsappMessage: 'Hello, I would like to learn more about JC Cabarcas Ingeniería and its services.', logoLabel: 'JC Cabarcas, home' },
}
