import { brandMessages, engineering, metrics, pillars, quoteTypes, sectors, solar, technology, values } from '../data/corporate.js'
export default {
  locale: 'es', seo: { title: 'JC Cabarcas Ingeniería SAS | Ingeniería, Energía y Tecnología', description: 'JC Cabarcas Ingeniería SAS integra ingeniería, energía solar y tecnología para proyectos nacionales e internacionales desde Barranquilla, Colombia.', ogDescription: 'Ingeniería, energía solar y tecnología para proyectos que trascienden fronteras.' },
  nav: { label: 'Navegación principal', open: 'Abrir menú', close: 'Cerrar menú', home: 'Inicio', items: [['nosotros', 'Nosotros'], ['soluciones', 'Soluciones'], ['proyectos', 'Proyectos'], ['sectores', 'Sectores'], ['tecnologia', 'Tecnología'], ['cotizar', 'Cotizar'], ['contacto', 'Contacto']], cta: 'Iniciar proyecto' }, language: { label: 'Seleccionar idioma', es: 'Español', en: 'Inglés', other: 'Otros idiomas', otherLabel: 'Abrir idiomas adicionales', menuTitle: 'Idiomas', official: 'Traducción oficial' },
  hero: { kicker: 'JC CABARCAS INGENIERÍA', line1: 'Diseñamos', line2: 'el futuro.', subtitle: brandMessages.heroSubtitle, solutions: 'Conoce nuestras soluciones', quote: 'Cotiza tu proyecto', explore: 'Explorar', location: 'Barranquilla · Colombia' },
  pillars: { eyebrow: 'Una visión integral', intro: 'Tres capacidades que trabajan como una sola para llevar cada proyecto más lejos.', items: pillars },
  engineering: { eyebrow: '01 · Ingeniería', title: 'Rigor técnico para proyectos que deben funcionar.', intro: 'Diseñamos, supervisamos y ejecutamos soluciones de infraestructura con una mirada integral: desde los estudios iniciales hasta la puesta en operación.', groups: engineering, cta: 'Consultar una solución de ingeniería', quoteType: 'Ingeniería' },
  solar: { eyebrow: '02 · Energía', title1: 'La energía del sol.', title2: 'Diseñada para rendir.', intro: 'Convertimos el potencial solar en sistemas confiables, medibles y preparados para las necesidades reales de hogares, empresas e infraestructura.', from: 'De la viabilidad', to: 'a la operación', process: 'Un solo equipo para estudiar, diseñar, implementar y mantener.', groups: solar, cta: 'Diseñar mi sistema solar', quoteType: 'Energía solar' },
  technology: { eyebrow: '03 · Tecnología', title: 'Tecnología que resuelve. Software que conecta.', intro: 'Creamos productos digitales y sistemas inteligentes alrededor de la operación. Soluciones construidas para crecer junto a cada organización.', groups: technology, cta: 'Consultar una solución tecnológica', quoteType: 'Software' },
  smart: { eyebrow: 'Solución diferencial', title1: 'Energía', title2: 'inteligente.', intro: 'Diseñamos sistemas energéticos que pueden ser monitoreados desde cualquier lugar.', description: 'Integramos ingeniería eléctrica, generación solar y software propio para visualizar generación, consumo, baterías, ahorro, alarmas, históricos, predicciones y estado de equipos.', cta: 'Construir una solución integrada', quoteType: 'Software', demo: 'Demostración visual · Datos no reales', center: 'Centro de energía', normal: 'Operación normal', metrics, online: 'Sistema en línea', conceptual: 'Vista conceptual' },
  sectors: { eyebrow: 'Sectores', title: 'Experiencia adaptable a cada entorno.', items: sectors },
  about: { eyebrow: 'Nosotros', title: 'Una compañía. Tres disciplinas. Una visión.', intro: 'Somos una compañía de Barranquilla que entiende la ingeniería como una plataforma para transformar. Combinamos conocimiento técnico, energía sostenible y desarrollo tecnológico para construir soluciones coherentes de principio a fin.', missionLabel: 'Misión', mission: 'Ser el aliado estratégico de nuestros clientes mediante soluciones integrales de ingeniería, energía y tecnología que aumenten la eficiencia, confiabilidad y sostenibilidad de sus proyectos.', visionLabel: 'Visión', vision: 'Consolidarnos como una compañía referente en soluciones integrales, reconocida por la innovación, calidad y capacidad de transformar necesidades complejas en soluciones eficientes y sostenibles.', valuesLabel: 'Nuestros valores', values },
  global: { eyebrow: brandMessages.globalEyebrow, title: brandMessages.globalTitle, description: brandMessages.globalDescription, capabilitiesLabel: 'Capacidades adaptables', capabilities: brandMessages.globalCapabilities, cta: 'Conversemos sobre tu proyecto' },
  projects: { eyebrow: 'Proyectos', title: 'Un espacio para mostrar resultados reales.', intro: 'Esta sección está preparada para documentar proyectos verificables a medida que se consolide su información.', placeholder: 'PRÓXIMAMENTE · ESTRUCTURA', cards: ['Ingeniería e infraestructura', 'Energía solar', 'Tecnología aplicada'], description: 'Ficha preparada para alcance, ubicación, solución y resultados verificados.' },
  quote: { eyebrow: 'Hablemos', title1: 'Cuéntanos sobre', title2: 'tu proyecto.', intro: 'Conversemos sobre el reto, el contexto y la solución que necesitas. Nuestro equipo revisará la información para orientar el siguiente paso.', direct: 'O escríbenos por WhatsApp', fields: { name: 'Nombre', company: 'Empresa', email: 'Correo', phone: 'Teléfono', type: 'Tipo de proyecto', description: 'Descripción del proyecto' }, placeholders: { name: 'Tu nombre', company: 'Nombre de la empresa', email: 'correo@empresa.com', phone: '320 641 8292', type: 'Selecciona una opción', description: 'Cuéntanos brevemente qué necesitas...' }, types: quoteTypes, submit: 'Solicitar asesoría', validating: 'Validando…', ready: 'Tu solicitud está lista. WhatsApp se abrió en una pestaña nueva para que confirmes el envío.', blocked: 'Tu solicitud está lista. El navegador bloqueó la pestaña;', openWhatsapp: 'abre WhatsApp aquí', error: 'Revisa los campos señalados antes de continuar.', privacy: 'Al continuar, prepararemos tu solicitud en WhatsApp. Tus datos no se almacenan todavía.', errors: { name: 'Por favor ingresa tu nombre.', company: 'Por favor ingresa el nombre de la empresa.', emailRequired: 'Por favor ingresa tu correo.', emailInvalid: 'Por favor ingresa un correo válido.', phoneRequired: 'Por favor ingresa un teléfono de contacto.', phoneInvalid: 'Por favor ingresa un teléfono internacional válido.', country: 'Por favor selecciona tu país.', type: 'Por favor selecciona un tipo de proyecto.', description: 'Por favor describe brevemente tu proyecto.' }, message: { greeting: 'Hola, JC Cabarcas Ingeniería.', request: 'Quiero solicitar asesoría para un proyecto.', name: 'Nombre', company: 'Empresa', country: 'País', phone: 'Teléfono', email: 'Correo', type: 'Tipo de proyecto', description: 'Descripción', closing: 'Quedo atento a su contacto.' } },
  country: { trigger: 'País y prefijo', searchLabel: 'Buscar país', searchPlaceholder: 'Buscar país, ISO o prefijo…', listLabel: 'Países y prefijos telefónicos', empty: 'No encontramos un país con esa búsqueda.' }, contact: { label: 'Contacto', international: brandMessages.internationalAttention },
  footer: { description: 'Integramos ingeniería, energía renovable y tecnología para transformar proyectos complejos en soluciones eficientes.', explore: 'Explora', contact: 'Contacto', rights: 'Todos los derechos reservados.', claim: 'Ingeniería · Energía · Tecnología', whatsappLabel: 'Contactar por WhatsApp', whatsapp: 'Hablemos', whatsappMessage: 'Hola, estoy interesado en conocer más sobre los servicios de JC Cabarcas Ingeniería.', logoLabel: 'JC Cabarcas, inicio' },
}
